title: [Translation Initiative for COVID-19]
description: [Providing machine-readable translation data related to the COVID-19 pandemic]
show_downloads: false
theme: jekyll-theme-minimal
github.is_project_page: false
google_analytics: "UA-167817988-1"
